version: '2'
services:
   db:
     image: postgres:latest
     ports:
       - "54320:5432"
     environment:
       POSTGRES_PASSWORD: password
       POSTGRES_DB: chitchat
     volumes:
       - ./initdb:/docker-entrypoint-initdb.d